name: Run on Push

# Disparador: Se ejecuta cuando se hace push al repositorio
on:
  push:
    branches:
      - '*'  # Puedes especificar otras ramas como 'develop' o usar '*' para todas las ramas

jobs:
  build:
    name: Build and Test on Push
    runs-on: self-hosted  # Usa un runner GitHub-hosted
    
    steps:
      # Paso 1: Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Paso 2: Configurar el entorno de Node.js (ejemplo)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
